<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class PlayerLeaderboardResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'player_id' => data_get($this->resource, 'player_id'),
            'player' => data_get($this->resource, 'player'),
            'games_played' => data_get($this->resource, 'games_played'),
            'points_per_game' => data_get($this->resource, 'points_per_game'),
            'rebounds_per_game' => data_get($this->resource, 'rebounds_per_game'),
            'assists_per_game' => data_get($this->resource, 'assists_per_game'),
            'turnovers_per_game' => data_get($this->resource, 'turnovers_per_game'),
            'steals_per_game' => data_get($this->resource, 'steals_per_game'),
            'blocks_per_game' => data_get($this->resource, 'blocks_per_game'),
            'minutes_per_game' => data_get($this->resource, 'minutes_per_game'),
            'field_goal_percentage' => data_get($this->resource, 'field_goal_percentage'),
            'three_point_percentage' => data_get($this->resource, 'three_point_percentage'),
            'free_throw_percentage' => data_get($this->resource, 'free_throw_percentage'),
            'innings_pitched_per_game' => data_get($this->resource, 'innings_pitched_per_game'),
            'era_per_game' => data_get($this->resource, 'era_per_game'),
            'whip_per_game' => data_get($this->resource, 'whip_per_game'),
            'strikeouts_pitched_per_game' => data_get($this->resource, 'strikeouts_pitched_per_game'),
            'walks_allowed_per_game' => data_get($this->resource, 'walks_allowed_per_game'),
            'hits_allowed_per_game' => data_get($this->resource, 'hits_allowed_per_game'),
            'home_runs_allowed_per_game' => data_get($this->resource, 'home_runs_allowed_per_game'),
            'estimated_epa_total' => data_get($this->resource, 'estimated_epa_total'),
            'estimated_epa_per_game' => data_get($this->resource, 'estimated_epa_per_game'),
            'estimated_epa_per_36' => data_get($this->resource, 'estimated_epa_per_36'),
            'estimated_epa_per_opportunity' => data_get($this->resource, 'estimated_epa_per_opportunity'),
            'passing_yards_per_game' => data_get($this->resource, 'passing_yards_per_game'),
            'passing_touchdowns_per_game' => data_get($this->resource, 'passing_touchdowns_per_game'),
            'completion_percentage' => data_get($this->resource, 'completion_percentage'),
            'interceptions_thrown_per_game' => data_get($this->resource, 'interceptions_thrown_per_game'),
            'passing_yards_total' => data_get($this->resource, 'passing_yards_total'),
            'passing_touchdowns_total' => data_get($this->resource, 'passing_touchdowns_total'),
            'interceptions_thrown_total' => data_get($this->resource, 'interceptions_thrown_total'),
            'passing_attempts_total' => data_get($this->resource, 'passing_attempts_total'),
            'passing_completions_total' => data_get($this->resource, 'passing_completions_total'),
            'passing_yards_gross_total' => data_get($this->resource, 'passing_yards_gross_total'),
            'passing_touchdown_percentage' => data_get($this->resource, 'passing_touchdown_percentage'),
            'interception_percentage' => data_get($this->resource, 'interception_percentage'),
            'games_with_interception' => data_get($this->resource, 'games_with_interception'),
            'games_with_interception_percentage' => data_get($this->resource, 'games_with_interception_percentage'),
            'yards_per_pass_thrown' => data_get($this->resource, 'yards_per_pass_thrown'),
            'passing_long_total' => data_get($this->resource, 'passing_long_total'),
            'sacks_taken_total' => data_get($this->resource, 'sacks_taken_total'),
            'sack_yards_lost_total' => data_get($this->resource, 'sack_yards_lost_total'),
            'passing_yards_net_total' => data_get($this->resource, 'passing_yards_net_total'),
            'net_yards_per_passing_play' => data_get($this->resource, 'net_yards_per_passing_play'),
            'qb_rating' => data_get($this->resource, 'qb_rating'),
            'passing_two_point_conversions_total' => data_get($this->resource, 'passing_two_point_conversions_total'),
            'passing_rushing_yards_total' => data_get($this->resource, 'passing_rushing_yards_total'),
            'qbr' => data_get($this->resource, 'qbr'),
            'rushing_yards_per_game' => data_get($this->resource, 'rushing_yards_per_game'),
            'rushing_touchdowns_per_game' => data_get($this->resource, 'rushing_touchdowns_per_game'),
            'yards_per_carry' => data_get($this->resource, 'yards_per_carry'),
            'receptions_per_game' => data_get($this->resource, 'receptions_per_game'),
            'receiving_yards_per_game' => data_get($this->resource, 'receiving_yards_per_game'),
            'rushing_yards_total' => data_get($this->resource, 'rushing_yards_total'),
            'rushing_touchdowns_total' => data_get($this->resource, 'rushing_touchdowns_total'),
            'rushing_attempts_total' => data_get($this->resource, 'rushing_attempts_total'),
            'rushing_long_total' => data_get($this->resource, 'rushing_long_total'),
            'rushing_two_point_conversions_total' => data_get($this->resource, 'rushing_two_point_conversions_total'),
            'receptions_total' => data_get($this->resource, 'receptions_total'),
            'receiving_yards_total' => data_get($this->resource, 'receiving_yards_total'),
            'yards_per_reception' => data_get($this->resource, 'yards_per_reception'),
            'receiving_touchdowns_total' => data_get($this->resource, 'receiving_touchdowns_total'),
            'receiving_long_total' => data_get($this->resource, 'receiving_long_total'),
            'pass_targets_total' => data_get($this->resource, 'pass_targets_total'),
            'catch_rate' => data_get($this->resource, 'catch_rate'),
            'receiving_two_point_conversions_total' => data_get($this->resource, 'receiving_two_point_conversions_total'),
            'rushing_receiving_yards_total' => data_get($this->resource, 'rushing_receiving_yards_total'),
            'rushing_receiving_touchdowns_total' => data_get($this->resource, 'rushing_receiving_touchdowns_total'),
            'kickoff_returns_total' => data_get($this->resource, 'kickoff_returns_total'),
            'kickoff_return_yards_total' => data_get($this->resource, 'kickoff_return_yards_total'),
            'yards_per_kickoff_return' => data_get($this->resource, 'yards_per_kickoff_return'),
            'kickoff_return_touchdowns_total' => data_get($this->resource, 'kickoff_return_touchdowns_total'),
            'kickoff_return_long_total' => data_get($this->resource, 'kickoff_return_long_total'),
            'kickoff_return_fair_catches_total' => data_get($this->resource, 'kickoff_return_fair_catches_total'),
            'punt_returns_total' => data_get($this->resource, 'punt_returns_total'),
            'punt_return_yards_total' => data_get($this->resource, 'punt_return_yards_total'),
            'yards_per_punt_return' => data_get($this->resource, 'yards_per_punt_return'),
            'punt_return_touchdowns_total' => data_get($this->resource, 'punt_return_touchdowns_total'),
            'punt_return_long_total' => data_get($this->resource, 'punt_return_long_total'),
            'punt_return_fair_catches_total' => data_get($this->resource, 'punt_return_fair_catches_total'),
            'tackles_per_game' => data_get($this->resource, 'tackles_per_game'),
            'sacks_per_game' => data_get($this->resource, 'sacks_per_game'),
            'def_interceptions_per_game' => data_get($this->resource, 'def_interceptions_per_game'),
            'passes_defended_per_game' => data_get($this->resource, 'passes_defended_per_game'),
            'fumbles_recovered_per_game' => data_get($this->resource, 'fumbles_recovered_per_game'),
            'tackles_total' => data_get($this->resource, 'tackles_total'),
            'sacks_total' => data_get($this->resource, 'sacks_total'),
            'def_interceptions_total' => data_get($this->resource, 'def_interceptions_total'),
            'passes_defended_total' => data_get($this->resource, 'passes_defended_total'),
            'fumbles_recovered_total' => data_get($this->resource, 'fumbles_recovered_total'),
            'field_goals_made_per_game' => data_get($this->resource, 'field_goals_made_per_game'),
            'extra_points_made_per_game' => data_get($this->resource, 'extra_points_made_per_game'),
            'field_goal_percentage_special' => data_get($this->resource, 'field_goal_percentage_special'),
            'extra_point_percentage' => data_get($this->resource, 'extra_point_percentage'),
            'field_goals_made_total' => data_get($this->resource, 'field_goals_made_total'),
            'field_goals_attempted_total' => data_get($this->resource, 'field_goals_attempted_total'),
            'extra_points_made_total' => data_get($this->resource, 'extra_points_made_total'),
            'extra_points_attempted_total' => data_get($this->resource, 'extra_points_attempted_total'),
        ];
    }
}
