<?php

return [
    'state_baseline' => [
        'enabled' => env('EPA_STATE_BASELINE_ENABLED', false),
        'min_sample_size' => env('EPA_STATE_BASELINE_MIN_SAMPLE_SIZE', 25),
    ],

    'profiles' => [
        'nba' => [
            'points' => 0.70,
            'assists' => 0.25,
            'rebounds_total' => 0.10,
            'steals' => 0.30,
            'blocks' => 0.30,
            'turnovers' => -0.30,
            'missed_field_goals' => -0.08,
            'missed_free_throws' => -0.05,
        ],
        'cbb' => [
            'points' => 0.62,
            'assists' => 0.25,
            'rebounds_total' => 0.14,
            'steals' => 0.30,
            'blocks' => 0.30,
            'turnovers' => -0.36,
            'missed_field_goals' => -0.10,
            'missed_free_throws' => -0.05,
        ],
        'nfl' => [
            'passing_yards' => 0.045,
            'passing_touchdowns' => 3.50,
            'interceptions_thrown' => -4.00,
            'sacks_taken' => -1.20,
            'sack_yards_lost' => -0.03,
            'passing_two_point_conversions' => 1.80,
            'rushing_yards' => 0.08,
            'rushing_touchdowns' => 5.00,
            'rushing_attempts' => -0.04,
            'rushing_two_point_conversions' => 1.80,
            'receptions' => 0.30,
            'receiving_yards' => 0.09,
            'receiving_touchdowns' => 5.00,
            'receiving_targets' => -0.02,
            'receiving_two_point_conversions' => 1.80,
            'kickoff_return_yards' => 0.03,
            'kickoff_return_touchdowns' => 5.50,
            'punt_return_yards' => 0.04,
            'punt_return_touchdowns' => 5.50,
            'tackles_total' => 0.12,
            'sacks' => 1.70,
            'interceptions' => 3.20,
            'passes_defended' => 0.45,
            'fumbles_recovered' => 2.20,
            'field_goals_made' => 2.60,
            'field_goals_attempted' => -0.20,
            'extra_points_made' => 1.00,
            'extra_points_attempted' => -0.05,
        ],
    ],
];
